# Generated by Django 5.2.1 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fantasy_team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pro_team',
            field=models.IntegerField(default=0),
        ),
    ]
