# Generated by Django 5.2.1 on 2025-05-28 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnAPI', '0002_update_player_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currently_rostered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_metric',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
