# Generated by Django 5.2.1 on 2025-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnAPI', '0003_add_draft_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currently_rostered',
            field=models.BooleanField(default=False),
        ),
    ]
