# Generated by Django 5.2.1 on 2025-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnAPI', '0004_update_currently_rostered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draft_metric',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
