# Generated by Django 5.2.1 on 2025-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnAPI', '0005_update_metric_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draft_team_id',
            field=models.IntegerField(default=0),
        ),
    ]
